// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoKey(arg1) {
  return window['go']['main']['App']['DoKey'](arg1);
}

export function LoadImage(arg1) {
  return window['go']['main']['App']['LoadImage'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
