// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoKey(arg1:string):Promise<void>;

export function LoadImage(arg1:number):Promise<main.FileItem>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
