// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoKey(arg1:string):Promise<void>;

export function GetPicDir():Promise<string>;

export function GetProjectFile():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function LoadImage():Promise<main.FileItem>;

export function SaveSettings(arg1:main.Settings,arg2:boolean):Promise<void>;
